Um erro fatal ocorreu:
Traceback (most recent call last):
  File "c:\Users\aysla\Documents\Jogo_Asrahel\Jogo\Arquivos\Game.py", line 556, in <module>
    main()
  File "c:\Users\aysla\Documents\Jogo_Asrahel\Jogo\Arquivos\Game.py", line 335, in main
    for arvore in arvores:
                  ^^^^^^^
UnboundLocalError: cannot access local variable 'arvores' where it is not associated with a value
